# Dynamic Programming
###  2017/03/09

In [1]:
# Finding nth Fibanacci Number 
def fib_bf(n):
    '''Brute Force Approach; Exponential time complexity'''
    if n == 0 or n == 1:
        return n
    else:
        return fib(n-1) + fib(n-2)
    
def fib_dict(n, d):
    '''Use a dictionary d to memorize found solutions to subproblems'''
    if n in d:
        return d[n]
    else:
        sol = fib_dict(n-1, d) + fib_dict(n-2, d)
        d[n] = sol
        print ("Insert entry {}:{}".format(n, sol))
        return sol
    
def fib(n):
    '''Use a linear array to store found solutions to subproblems'''
    sol = [-1 for i in range(n+1)] # list comprehension
    sol[0] = 0
    sol[1] = 1
    for i in range(2, n+1):
        sol[i] = sol[i-1] + sol[i-2]
    return sol
    

In [3]:
d = {0:0, 1:1}
fib(10)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55]

In [20]:
# Finding a Longest Common Subsequence of two strings
def lcs_bf(x, y):
    '''Brute Force Approach'''
    if len(x) == 0 or len(y) == 0:
        return 0
    else:
        if x[-1] == y[-1]:
            return lcs_bf(x[:-1], y[:-1]) + 1
        else:
            return max(lcs_bf(x[:-1], y[:]), lcs_bf(x[:], y[:-1]))
        

In [4]:
def lcs_dict(x, y, d):
    '''Use a dictionary d to store found solutions to subproblems'''
    k = str(len(x))+'-'+str(len(y)) # Use lengths of strings as key
    if k in d:
        return d[k]
    else:
        if len(x) == 0 or len(y) == 0:
            lcs_length = 0
        else:
            if x[-1] == y[-1]:
                lcs_length = lcs_dict(x[:-1], y[:-1], d) + 1
            else:
                lcs_length = max(lcs_dict(x[:-1], y[:], d), lcs_dict(x[:], y[:-1], d))
            d[k] = lcs_length
            print ("Insert {}:{}".format(k, lcs_length))
        return lcs_length
        

In [5]:
d = dict()
lcs_dict("NTHU Univ", "NCTU Unev", d)

Insert 1-1:1
Insert 1-2:1
Insert 1-3:1
Insert 1-4:1
Insert 1-5:1
Insert 1-6:1
Insert 1-7:1
Insert 1-8:1
Insert 2-3:2
Insert 2-4:2
Insert 2-5:2
Insert 2-6:2
Insert 2-7:2
Insert 2-8:2
Insert 2-1:1
Insert 2-2:1
Insert 3-1:1
Insert 3-2:1
Insert 3-3:2
Insert 3-4:2
Insert 3-5:2
Insert 3-6:2
Insert 3-7:2
Insert 3-8:2
Insert 4-6:3
Insert 4-7:3
Insert 4-8:3
Insert 4-4:3
Insert 5-5:4
Insert 5-6:4
Insert 5-7:4
Insert 5-8:4
Insert 6-6:5
Insert 6-7:5
Insert 6-8:5
Insert 7-7:6
Insert 7-8:6
Insert 4-1:1
Insert 4-2:1
Insert 4-3:2
Insert 5-1:1
Insert 5-2:1
Insert 5-3:2
Insert 6-4:3
Insert 6-5:4
Insert 6-1:1
Insert 6-2:1
Insert 6-3:2
Insert 7-1:1
Insert 7-2:1
Insert 7-3:2
Insert 7-4:3
Insert 7-5:4
Insert 7-6:5
Insert 8-1:1
Insert 8-2:1
Insert 8-3:2
Insert 8-4:3
Insert 8-5:4
Insert 8-6:5
Insert 8-7:6
Insert 8-8:6
Insert 9-9:7


7

In [6]:
import numpy as np

def lcs(x, y):
    '''Use an array to store found solutions; fill it up from upper left to lower right'''
    num_r = len(x)+1
    num_c = len(y)+1
    a = np.zeros((num_r, num_c), dtype=int)
    for r in range(1, num_r):
        for c in range(1, num_c):
            if x[r-1] == y[c-1]:
                a[r, c] = a[r-1, c-1] + 1
            else:
                a[r, c] = max(a[r-1, c], a[r, c-1])
    print (a)
    return a[-1, -1]          

In [7]:
lcs("NTHU Univ", "NCTU Unev")

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 1]
 [0 1 1 2 2 2 2 2 2 2]
 [0 1 1 2 2 2 2 2 2 2]
 [0 1 1 2 3 3 3 3 3 3]
 [0 1 1 2 3 4 4 4 4 4]
 [0 1 1 2 3 4 5 5 5 5]
 [0 1 1 2 3 4 5 6 6 6]
 [0 1 1 2 3 4 5 6 6 6]
 [0 1 1 2 3 4 5 6 6 7]]


7

In [8]:
# Text Justification

def tj_greedy(text, width):
    '''A greedy approach'''
    word_list = text.split()
    i = 0
    while i < len(word_list):
        line = ''
        usage = 0
        while (i < len(word_list) and
               usage < width and 
               len(word_list[i])+usage < width):
            if line != '':
                line = line +  " " + word_list[i]
                usage += len(word_list[i]) + 1
            else:
                line = word_list[i]
                usage += len(word_list[i])
            i += 1
        print ("waste=", width-usage, line)
    return

In [9]:
text = "National Tsing Hua University. This is the worst of time. This is the best of time."

tj_greedy(text,20)

waste= 2 National Tsing Hua
waste= 1 University. This is
waste= 2 the worst of time.
waste= 1 This is the best of
waste= 15 time.
