## Top Ten Important Algorithm Machine Problem 2
1.	Fibonacci number generation
2.	Longest Common Subsequence Algorithm
3.	Text Justification
4.	Matrix Chain Multiplication
5.	Any Dynamic Programming Algorithm you find important

# 1. Fibonacci number generation

In [16]:
'''Fibonacci(n) will print n Fibonacci numbers where n is a non-negative integer '''
def Fibonacci(n):
    '''Use a linear array to store found solutions to subproblems'''
    # create a n-numbers list where all the elements are 0
    sol = [0 for i in range(n+1)] # list comprehension
    sol[0] = 0 # where n=1
    sol[1] = 1 # where n=2
    for i in range(2, n+1):
        sol[i] = sol[i-1] + sol[i-2]
    return sol

In [17]:
# example
Fibonacci(10)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55]

# 2. Longest Common Subsequence Algorithm

In [20]:
'''lcs(input1, input2) will print the table of DP and the lcs of input 1 & input 2.'''
import numpy as np #array

def lcs(input1, input2):
    '''Use an table to store found solutions'''
    num_row = len(input1)+1
    num_col = len(input2)+1
    # create a zero-matrix table with given row & colunm 
    table = np.zeros((num_row, num_col), dtype=int)
    
    # compute the value from upper left to lower right
    for row in range(1, num_row):
        for col in range(1, num_col):
            # 字相同時: 左上+1
            if input1[row-1] == input2[col-1]:
                table[row, col] = table[row-1, col-1] + 1
            # 字不同時: max(上,左) 
            else:
                table[row, col] = max(table[row-1, col], table[row, col-1])
    print (table)
    return table[-1, -1]          

In [21]:
lcs("NTHU Univ", "NCTU Unev")

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 1]
 [0 1 1 2 2 2 2 2 2 2]
 [0 1 1 2 2 2 2 2 2 2]
 [0 1 1 2 3 3 3 3 3 3]
 [0 1 1 2 3 4 4 4 4 4]
 [0 1 1 2 3 4 5 5 5 5]
 [0 1 1 2 3 4 5 6 6 6]
 [0 1 1 2 3 4 5 6 6 6]
 [0 1 1 2 3 4 5 6 6 7]]


7

# 3. Text Justification

In [63]:
'''tj_dict("imput text", character number limit) will return the minimum cost of every [start] word'''
# Use a dictionary to store found solutions to subproblems

def tj_dict(text, width):
    word_list = text.split()
    d = dict()
    return tj_dict_engine(word_list, width, 0, len(word_list)-1, d)

def tj_dict_engine(wl, width, start, end, d):
    if start > end:
        return 0
    # the order of the word [start]-[end] 
    key = str(start)+'-'+str(end)
    #if the cost is already in dictionary, just return the value
    if key in d:
        return d[key]
    
    candidates = []
    usage = 0
    i = start
    # go through the word list until the end
    while (i <= end and
           usage + len(wl[i]) <= width):
        usage += len(wl[i]) + 1
        candidates.append((i, (width-(usage-1))**2))
        i += 1
    # calculate the minimum cost of all the candidates    
    min_cost = min([t[1] + tj_dict_engine(wl, width, t[0]+1, end, d) 
                for t in candidates])
    # save the minimum cost into dictionary
    d[key] = min_cost
    
    print ("key{}: {}".format(key, min_cost))
    return min_cost

In [64]:
text = "I see Barsad, and Cly, Defarge, The Vengeance [a lieutenant of Madame Defarge], the Juryman, the Judge, long ranks of the new oppressors who have risen on the destruction of the old, perishing by this retributive instrument, before it shall cease out of its present use. I see a beautiful city and a brilliant people rising from this abyss, and, in their struggles to be truly free, in their triumphs and defeats, through long years to come, I see the evil of this time and of the previous time of which this is the natural birth, gradually making expiation for itself and wearing out. I see the lives for which I lay down my life, peaceful, useful, prosperous and happy, in that England which I shall see no more. I see Her with a child upon her bosom, who bears my name. I see her father, aged and bent, but otherwise restored, and faithful to all men in his healing office, and at peace. I see the good old man [Mr. Lorry], so long their friend, in ten years' time enriching them with all he has, and passing tranquilly to his reward. I see that I hold a sanctuary in their hearts, and in the hearts of their descendants, generations hence. I see her, an old woman, weeping for me on the anniversary of this day. I see her and her husband, their course done, lying side by side in their last earthly bed, and I know that each was not more honoured and held sacred in the other's soul, than I was in the souls of both. I see that child who lay upon her bosom and who bore my name, a man winning his way up in that path of life which once was mine. I see him winning it so well, that my name is made illustrious there by the light of his. I see the blots I threw upon it, faded away. I see him, fore-most of just judges and honoured men, bringing a boy of my name, with a forehead that I know and golden hair, to this place—then fair to look upon, with not a trace of this day's disfigurement—and I hear him tell the child my story, with a tender and a faltering voice. It is a far, far better thing that I do, than I have ever done; it is a far, far better rest that I go to than I have ever known."
tj_dict(text, 80)

key411-411: 5476
key410-411: 4761
key409-411: 4096
key408-411: 3844
key407-411: 3249
key406-411: 2916
key405-411: 2601
key404-411: 2401
key403-411: 1936
key402-411: 1521
key401-411: 1024
key400-411: 784
key399-411: 529
key398-411: 441
key397-411: 324
key396-411: 225
key395-411: 81
key394-411: 16
key393-411: 3202
key392-411: 3042
key391-411: 2677
key390-411: 2393
key389-411: 2249
key388-411: 1924
key387-411: 1568
key386-411: 1205
key385-411: 1013
key384-411: 802
key383-411: 724
key382-411: 613
key381-411: 514
key380-411: 325
key379-411: 117
key378-411: 97
key377-411: 41
key376-411: 2297
key375-411: 2193
key374-411: 1934
key373-411: 1589
key372-411: 1454
key371-411: 1202
key370-411: 1048
key369-411: 869
key368-411: 739
key367-411: 614
key366-411: 550
key365-411: 166
key364-411: 90
key363-411: 45
key362-411: 1983
key361-411: 1731
key360-411: 1643
key359-411: 1489
key358-411: 1304
key357-411: 1094
key356-411: 935
key355-411: 860
key354-411: 719
key353-411: 554
key352-411: 391
key351-411: 3

348

# 4.	Matrix Chain Multiplication

In [31]:
"""Fill up the upper triangle of a table following the order discovered by the Dictionary Method"""
import numpy as np

def cm_loop(chain):
    N = len(chain)
    # create a N*N zero-matrix 
    table = np.zeros((N, N), dtype = int)
    if N <= 1: # 0*0 matrix
        return 0
    else:
        for row in range(N-1, -1, -1):
            # 斜對角
            table[row, row] = 0
            for col in range(row+1, N):
                table[row, col] = min([table[row, i] +
                                 table[i+1, col] +
                                 chain[row][0]*chain[i][1]*chain[col][1]
                                 for i in range(row, col)]) 
    return table

In [32]:
chain = [(3, 5), (5, 4), (4, 2), (2, 9)]
cm_loop(chain)

array([[  0,  60,  70, 124],
       [  0,   0,  40, 130],
       [  0,   0,   0,  72],
       [  0,   0,   0,   0]])

# 5.	0-1 Knapsack Problem

In [54]:
'''knapsack("weight-value", maximum weight of bag)'''

# v = list of item values or profit
# w = list of item weight or cost
# W = max weight or max cost for the knapsack
def zeroOneKnapsack(v, w, W):
    # c is the cost matrix
    c = []
    n = len(v)
    c = zeros(n,W+1)
    for i in range(0,n):
        #for ever possible weight
        for j in range(0,W+1):
            #can we add this item to this?
            if (w[i] > j):
                c[i][j] = c[i-1][j]
            else:
                c[i][j] = max(c[i-1][j],v[i] +c[i-1][j-w[i]])
    return [c[n-1][W], getUsedItems(w,c)]

# w = list of item weight or cost
# c = the cost matrix created by DP
def getUsedItems(w,c):
    # item count
    i = len(c)-1
    currentW =  len(c[0])-1
    # set everything not taged
    taged = []
    for i in range(i+1):
        taged.append(0)
    while (i >= 0 and currentW >=0):
        if (i==0 and c[i][currentW] >0 )or c[i][currentW] != c[i-1][currentW]:
            taged[i] =1
            currentW = currentW-w[i]
        i = i-1
    return taged

# create a rows*cols zero-element table
def zeros(rows,cols):
    row = []
    data = []
    for i in range(cols):
        row.append(0)
    for i in range(rows):
        data.append(row[:])
    return data

def knapsack(input_items, maxCost):
    items = input_items.split(',')
    w = []
    v = []
    total =0
    for item in items:
        nums = item.split('-')
        w.append(int(nums[0]))
        v.append(int(nums[1]))

    answer = zeroOneKnapsack(v,w,maxCost)
    print ("my bag can hold %d kgs, with profit: $%d." % (maxCost,answer[0]))
    print ("by taking item(s): "),
    for i in range(len(answer[1])):
        if (answer[1][i] != 0):
            print( i+1)

In [55]:
knapsack("1-2,2-5,3-10,4-4,5-9,6-13",10)

my bag can hold 10 kgs, with profit: $25.
by taking item(s): 
1
3
6
