## Top Ten Important Algorithm Machine Problem 2
1.	Fibonacci number generation
2.	Longest Common Subsequence Algorithm
3.	Text Justification
4.	Matrix Chain Multiplication
5.	Any Dynamic Programming Algorithm you find important

# 1. Fibonacci number generation

In [16]:
'''Fibonacci(n) will print n Fibonacci numbers where n is a non-negative integer '''
def Fibonacci(n):
    '''Use a linear array to store found solutions to subproblems'''
    # create a n-numbers list where all the elements are 0
    sol = [0 for i in range(n+1)] # list comprehension
    sol[0] = 0 # where n=1
    sol[1] = 1 # where n=2
    for i in range(2, n+1):
        sol[i] = sol[i-1] + sol[i-2]
    return sol

In [17]:
# example
Fibonacci(10)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55]

# 2. Longest Common Subsequence Algorithm
references:http://www.csie.ntnu.edu.tw/~u91029/LongestCommonSubsequence.html

In [20]:
'''lcs(input1, input2) will print the table of DP and the lcs of input 1 & input 2.'''
import numpy as np #array

def lcs(input1, input2):
    '''Use an table to store found solutions'''
    num_row = len(input1)+1
    num_col = len(input2)+1
    # create a zero-matrix table with given row & colunm 
    table = np.zeros((num_row, num_col), dtype=int)
    
    # compute the value from upper left to lower right
    for row in range(1, num_row):
        for col in range(1, num_col):
            # 字相同時: 左上+1
            if input1[row-1] == input2[col-1]:
                table[row, col] = table[row-1, col-1] + 1
            # 字不同時: max(上,左) 
            else:
                table[row, col] = max(table[row-1, col], table[row, col-1])
    print (table)
    return table[-1, -1]          

In [21]:
lcs("NTHU Univ", "NCTU Unev")

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 1]
 [0 1 1 2 2 2 2 2 2 2]
 [0 1 1 2 2 2 2 2 2 2]
 [0 1 1 2 3 3 3 3 3 3]
 [0 1 1 2 3 4 4 4 4 4]
 [0 1 1 2 3 4 5 5 5 5]
 [0 1 1 2 3 4 5 6 6 6]
 [0 1 1 2 3 4 5 6 6 6]
 [0 1 1 2 3 4 5 6 6 7]]


7

# 3. Text Justification

In [94]:
'''Base on the code mentioned in class, I wrote two new functions. 
    One is to print out the text; the other is to calculate the cost.'''

def tj_dict(text, width):
    word_list = text.split()
    d = dict()
    tj_dict_engine(word_list, width, 0, len(word_list)-1, d)
    tj_bt(word_list, width, 0, len(word_list)-1, d)

# this fuction will save the costs in a dictionary type and return the minimum
def tj_dict_engine(wl, width, start, end, d):
    if start > end:
        return 0
    key = str(start)+'-'+str(end)
    if key in d:
        return d[key][0]
    candidates = []
    usage = 0
    i = start
    while i <= end and usage + len(wl[i]) <= width:
        usage += len(wl[i]) + 1
        candidates.append((i, (width-(usage-1))**2))
        i += 1
    min_cost, min_word = min([(t[1] + tj_dict_engine(wl, width, t[0]+1, end, d), t[0])
                   for t in candidates])
    d[key] = (min_cost, min_word)
    return min_cost

# calculate the cost
def cost(line, width):
    return (width - len(line)) ** 2

# print out the text
def tj_bt(wl, width, start, end, d):
    key = str(start)+'-'+str(end)
    if start > end:
        return
    line = ' '.join(wl[start:d[key][1]+1])
    print("cost=", cost(line, width)) 
    print(line)
    tj_bt(wl, width, d[key][1]+1, end, d)
    return

In [95]:
text = "I see Barsad, and Cly, Defarge, The Vengeance [a lieutenant of Madame Defarge], the Juryman, the Judge, long ranks of the new oppressors who have risen on the destruction of the old, perishing by this retributive instrument, before it shall cease out of its present use. I see a beautiful city and a brilliant people rising from this abyss, and, in their struggles to be truly free, in their triumphs and defeats, through long years to come, I see the evil of this time and of the previous time of which this is the natural birth, gradually making expiation for itself and wearing out. I see the lives for which I lay down my life, peaceful, useful, prosperous and happy, in that England which I shall see no more. I see Her with a child upon her bosom, who bears my name. I see her father, aged and bent, but otherwise restored, and faithful to all men in his healing office, and at peace. I see the good old man [Mr. Lorry], so long their friend, in ten years' time enriching them with all he has, and passing tranquilly to his reward. I see that I hold a sanctuary in their hearts, and in the hearts of their descendants, generations hence. I see her, an old woman, weeping for me on the anniversary of this day. I see her and her husband, their course done, lying side by side in their last earthly bed, and I know that each was not more honoured and held sacred in the other's soul, than I was in the souls of both. I see that child who lay upon her bosom and who bore my name, a man winning his way up in that path of life which once was mine. I see him winning it so well, that my name is made illustrious there by the light of his. I see the blots I threw upon it, faded away. I see him, fore-most of just judges and honoured men, bringing a boy of my name, with a forehead that I know and golden hair, to this place—then fair to look upon, with not a trace of this day's disfigurement—and I hear him tell the child my story, with a tender and a faltering voice. It is a far, far better thing that I do, than I have ever done; it is a far, far better rest that I go to than I have ever known."
tj_dict(text, 80)

cost= 1
I see Barsad, and Cly, Defarge, The Vengeance [a lieutenant of Madame Defarge],
cost= 36
the Juryman, the Judge, long ranks of the new oppressors who have risen on
cost= 16
the destruction of the old, perishing by this retributive instrument, before
cost= 9
it shall cease out of its present use. I see a beautiful city and a brilliant
cost= 25
people rising from this abyss, and, in their struggles to be truly free, in
cost= 4
their triumphs and defeats, through long years to come, I see the evil of this
cost= 25
time and of the previous time of which this is the natural birth, gradually
cost= 16
making expiation for itself and wearing out. I see the lives for which I lay
cost= 9
down my life, peaceful, useful, prosperous and happy, in that England which I
cost= 16
shall see no more. I see Her with a child upon her bosom, who bears my name.
cost= 16
I see her father, aged and bent, but otherwise restored, and faithful to all
cost= 16
men in his healing office, and at peace. I see

# 4.	Matrix Chain Multiplication

In [31]:
"""Fill up the upper triangle of a table following the order discovered by the Dictionary Method"""
import numpy as np

def cm_loop(chain):
    N = len(chain)
    # create a N*N zero-matrix 
    table = np.zeros((N, N), dtype = int)
    if N <= 1: # 0*0 matrix
        return 0
    else:
        for row in range(N-1, -1, -1):
            # 斜對角
            table[row, row] = 0
            for col in range(row+1, N):
                table[row, col] = min([table[row, i] +
                                 table[i+1, col] +
                                 chain[row][0]*chain[i][1]*chain[col][1]
                                 for i in range(row, col)]) 
    return table

In [32]:
chain = [(3, 5), (5, 4), (4, 2), (2, 9)]
cm_loop(chain)

array([[  0,  60,  70, 124],
       [  0,   0,  40, 130],
       [  0,   0,   0,  72],
       [  0,   0,   0,   0]])

# 5.	0-1 Knapsack Problem
I learned this DP solution form the course introduction to algorithm

In [54]:
'''knapsack("weight-value", maximum weight of bag)'''

# v = list of item values or profit
# w = list of item weight or cost
# W = max weight or max cost for the knapsack
def zeroOneKnapsack(v, w, W):
    # c is the cost matrix
    c = []
    n = len(v)
    c = zeros(n,W+1)
    for i in range(0,n):
        #for ever possible weight
        for j in range(0,W+1):
            #can we add this item to this?
            if (w[i] > j):
                c[i][j] = c[i-1][j]
            else:
                c[i][j] = max(c[i-1][j],v[i] +c[i-1][j-w[i]])
    return [c[n-1][W], getUsedItems(w,c)]

# w = list of item weight or cost
# c = the cost matrix created by DP
def getUsedItems(w,c):
    # item count
    i = len(c)-1
    currentW =  len(c[0])-1
    # set everything not taged
    taged = []
    for i in range(i+1):
        taged.append(0)
    while (i >= 0 and currentW >=0):
        if (i==0 and c[i][currentW] >0 )or c[i][currentW] != c[i-1][currentW]:
            taged[i] =1
            currentW = currentW-w[i]
        i = i-1
    return taged

# create a rows*cols zero-element table
def zeros(rows,cols):
    row = []
    data = []
    for i in range(cols):
        row.append(0)
    for i in range(rows):
        data.append(row[:])
    return data

def knapsack(input_items, maxCost):
    items = input_items.split(',')
    w = []
    v = []
    total =0
    for item in items:
        nums = item.split('-')
        w.append(int(nums[0]))
        v.append(int(nums[1]))

    answer = zeroOneKnapsack(v,w,maxCost)
    print ("my bag can hold %d kgs, with profit: $%d." % (maxCost,answer[0]))
    print ("by taking item(s): "),
    for i in range(len(answer[1])):
        if (answer[1][i] != 0):
            print( i+1)

In [55]:
knapsack("1-2,2-5,3-10,4-4,5-9,6-13",10)

my bag can hold 10 kgs, with profit: $25.
by taking item(s): 
1
3
6
